# Site
name: "GLUG MVIT"
title: "GLUG MVIT"
description: "Community of FOSS developers from Sir M. Visvesvaraya Institute of Technology"
meta_description: "Technical community at Sir MVIT, Bangalore"
logo: 'assets/images/logo_full_rect.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'glugmvit@gmail.com'
# google_analytics: 'UA-46278016-1'
disqus: 'glugmvit'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  absingh:
    name: Abhijeet Singh
    display_name: Abhijeet Singh
    gravatar: a737e0e0b617487e706c406b0b80ef5d
    email: contact.abhijeetsingh@gmail.com
    web: https://www.absingh.com
    twitter: https://twitter.com/cse_as
    description: "Neighbourhood friendly Software Engineer.\nGLUG Lead | Microsoft Student Partner | AI Developer"
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge